### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by ChetanBhasin** [maxigit/sql-fragment#1]
Hey! Just wanted to get an idea of the status of this project. Do you think this would ever be added to Hackage/Stackage, or is it just an experimental project?

**Comment by maxigit** [comment]
It is experimental, but I would love to add it at some point to Hackage/Stackage. But I'm short of resources and nobody seems interested. At the moment, It only works with an old LTS, mainly because I used dimensional, which has been refactored heavily. The best way to upgrade it would be to just remove the dependency with dimensional. Another issue is that type inference makes it harder to use than expected. I was waiting for injective type families to solve it but didn't have time since. Apart from that, it work perfectly well, even though some improvement are posslible. Help and PR are welcome.

**Comment by ChetanBhasin** [comment]
Ah, I see. I've been spending a lot of time trying to understand Opaleye lately, but this also seems like an interesting project.
I'll spend some more time working with Opaleye, and if it takes way too much time, I'd love to contribute here.

**Comment by maxigit** [comment]
Have you tried sql-fragment yet, what is your haskell experience ?
You can find the doc here
http://maxigit.github.io/sql-fragment/Database-SQLFragment.html

And then the operator doc might be the best way to start
http://maxigit.github.io/sql-fragment/Database-SQLFragment-Operators.html

I'll be happy to help if you have any problem.

**Comment by ChetanBhasin** [comment]
Yeah, I played around a bit with your code. I'm still not very mature with Haskell, but I'm making good progress.
